### ISSUE TITLE
Value Error: Optimizing a parameter that doesn't require gradients

### ISSUE THREAD

**Issue by hufengshuo07** [chengdazhi/Deformable-Convolution-V2-PyTorch#36]
I try to replace all the conv2D with ModulatedDeformConvPack, but encounter this problem.Could you provide some advices, which parameters maybe influence? 
This's the log:

DCN_FastPose_SE(
  (preact): DCN_SEResnet(
    (conv1): ModulatedDeformConvPack(
      (conv_offset_mask): Conv2d(3, 294, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3))
    )
    (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (se): SELayer(
          (fc): Sequential(
            (0): Linear(in_features=128, out_features=128, bias=True)
            (1): ReLU(inplace)
            (2): Linear(in_features=128, out_features=128, bias=True)
            (3): Sigmoid()
          )
        )
        (downsample): Sequential(
          (0): ModulatedDeformConvPack(
            (conv_offset_mask): Conv2d(32, 6, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (2): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(32, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer2): Sequential(
      (0): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 54, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (se): SELayer(
          (fc): Sequential(
            (0): Linear(in_features=256, out_features=256, bias=True)
            (1): ReLU(inplace)
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): Sigmoid()
          )
        )
        (downsample): Sequential(
          (0): ModulatedDeformConvPack(
            (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(2, 2))
          )
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (2): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (3): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(64, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer3): Sequential(
      (0): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (se): SELayer(
          (fc): Sequential(
            (0): Linear(in_features=512, out_features=512, bias=True)
            (1): ReLU(inplace)
            (2): Linear(in_features=512, out_features=512, bias=True)
            (3): Sigmoid()
          )
        )
        (downsample): Sequential(
          (0): ModulatedDeformConvPack(
            (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(2, 2))
          )
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (2): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (3): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (4): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (5): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(128, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer4): Sequential(
      (0): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 54, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (se): SELayer(
          (fc): Sequential(
            (0): Linear(in_features=1024, out_features=1024, bias=True)
            (1): ReLU(inplace)
            (2): Linear(in_features=1024, out_features=1024, bias=True)
            (3): Sigmoid()
          )
        )
        (downsample): Sequential(
          (0): ModulatedDeformConvPack(
            (conv_offset_mask): Conv2d(512, 6, kernel_size=(1, 1), stride=(2, 2))
          )
          (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(1024, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (2): Bottleneck(
        (conv1): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(1024, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): ModulatedDeformConvPack(
          (conv_offset_mask): Conv2d(256, 6, kernel_size=(1, 1), stride=(1, 1))
        )
        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
  )
  (suffle1): PixelShuffle(upscale_factor=2)
  (duc1): DCN_DUC(
    (conv): ModulatedDeformConvPack(
      (conv_offset_mask): Conv2d(256, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (bn): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (pixel_shuffle): PixelShuffle(upscale_factor=2)
  )
  (duc2): DCN_DUC(
    (conv): ModulatedDeformConvPack(
      (conv_offset_mask): Conv2d(128, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace)
    (pixel_shuffle): PixelShuffle(upscale_factor=2)
  )
  (conv_out): ModulatedDeformConvPack(
    (conv_offset_mask): Conv2d(64, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
)
Create new model
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main()
  File "train.py", line 142, in main
    weight_decay=opt.weightDecay)
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/rmsprop.py", line 41, in __init__
    super(RMSprop, self).__init__(params, defaults)
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/optimizer.py", line 43, in __init__
    self.add_param_group(param_group)
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/optimizer.py", line 193, in add_param_group
    raise ValueError("optimizing a parameter that doesn't require gradients")
ValueError: optimizing a parameter that doesn't require gradients

**Comment by hufengshuo07** [comment]
Ｉsolve this problem by adding a filter:
optimizer = torch.optim.SGD( filter(lambda p: p.requires_grad, model.parameters())
but a new problem appeared. Could you give some help?

Create new model
############# Starting Epoch 0 #############
loss: 0.01542340 | acc: 1.54:   0%|                                                               | 1/17291 [00:01<9:12:33,  1.92s/it]Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main()
  File "train.py", line 173, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "train.py", line 31, in train
    out = m(inps)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sure/H/train_sppe/src/models/DCN_FastPose.py", line 41, in forward
    out = self.preact(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sure/H/train_sppe/src/models/layers/DCN_SE_Resnet.py", line 84, in forward
    x = self.layer3(x)  # 1024 * h/16 * w/16
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sure/H/train_sppe/src/models/layers/DCN_SE_Resnet.py", line 39, in forward
    out = self.conv3(out)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sure/H/train_sppe/src/DCNv2/modules/modulated_dcn.py", line 73, in forward
    return func(input, offset, mask, self.weight, self.bias)
  File "/media/sure/H/train_sppe/src/DCNv2/functions/modulated_dcn_func.py", line 36, in forward
    self.deformable_groups)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: cublas runtime error : an internal operation failed at /pytorch/aten/src/THC/THCBlas.cu:249
