### ISSUE TITLE
ImportError:    : undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by qianzhang2018** [chengdazhi/Deformable-Convolution-V2-PyTorch#44]
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main()
  File "train.py", line 138, in main
    model = create_model(opt) # model loss optimize
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/__init__.py", line 9, in create_model
    from .SR_model import SRModel as M
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/SR_model.py", line 7, in <module>
    import models.networks as networks
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/networks.py", line 3, in <module>
    import models.modules.SRResNet_arch as SRResNet_arch
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/modules/SRResNet_arch.py", line 4, in <module>
    import models.modules.module_util as mutil
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/modules/module_util.py", line 7, in <module>
    from deformable.modules.modulated_deform_conv import ModulatedDeformConv, _ModulatedDeformConv, ModulatedDeformConvPack
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/modules/deformable/modules/__init__.py", line 1, in <module>
    from .deform_conv import DeformConv, _DeformConv, DeformConvPack
  File "/mnt/ftp/code/zq/realsr/de_BasicSR-master/codes/models/modules/deformable/modules/deform_conv.py", line 12, in <module>
    from functions.deform_conv_func import DeformConvFunction
  File "/home/zq/anaconda3/envs/realsr/lib/python3.6/site-packages/DCN-1.0-py3.6-linux-x86_64.egg/functions/__init__.py", line 1, in <module>
    from .deform_conv_func import DeformConvFunction
  File "/home/zq/anaconda3/envs/realsr/lib/python3.6/site-packages/DCN-1.0-py3.6-linux-x86_64.egg/functions/deform_conv_func.py", line 13, in <module>
    import DCN
ImportError: /home/zq/anaconda3/envs/realsr/lib/python3.6/site-packages/DCN-1.0-py3.6-linux-x86_64.egg/DCN.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by KelvinHuang666** [comment]
I met the simple question...

Traceback (most recent call last):
  File "demo.py", line 136, in <module>
    demo()
  File "demo.py", line 82, in demo
    from models.yolov3_baseline import YOLOv3
  File "/asff/models/yolov3_baseline.py", line 5, in <module>
    from .network_blocks import *
  File "/asff/models/network_blocks.py", line 5, in <module>
    from utils.DCN.modules.deform_conv2d import DeformConv2d
  File "/asff/utils/DCN/modules/__init__.py", line 1, in <module>
    from .deform_conv2d import DeformConv2d, _DeformConv2d, DeformConv2dPack, DeformConv2dPackMore
  File "/asff/utils/DCN/modules/deform_conv2d.py", line 12, in <module>
    from ..functions.deform_conv2d_func import DeformConv2dFunction
  File "/asff/utils/DCN/functions/__init__.py", line 1, in <module>
    from .deform_conv2d_func import DeformConv2dFunction
  File "/asff/utils/DCN/functions/deform_conv2d_func.py", line 13, in <module>
    import DCN
ImportError: /usr/local/lib/python3.6/dist-packages/DCN-1.0-py3.6-linux-x86_64.egg/DCN.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
root@0ad4f68fc474:/asff#

**Comment by WangZhaoxue000** [comment]
the same problem...

**Comment by KelvinHuang666** [comment]
change your torch version

**Comment by WangZhaoxue000** [comment]
torch.__version__ ='1.3.1', torchvision.__version__='0.4.2'
still got the error

**Comment by myselvess** [comment]
> torch.**version** ='1.3.1', torchvision.**version**='0.4.2'
> still got the error

same version, have you solve this problem?

**Comment by Todd-Qi** [comment]
> change your torch version

Hello, which version of PyTorch do you use? 
I met the same problem。 I' using Pytorch 1.0.1 and CUDA 10.0

**Comment by WeixiongLin** [comment]
Same here, I use torch 1.0.1. I tried CUDA 10.0 and 9.2, they don't work.

**Comment by ted-chl** [comment]
I also met error with using torch 1.0.0, CUDA 10.2 (also in torch 1.10.0)

**Comment by yukistavailable** [comment]
I succeeded in installing DCN and importing it by the solution below. But I don't know if it works fine for other people.
1. [clone this repository](https://github.com/GOATmessi7/ASFF/tree/09f558863ae297663ec476f52a90c0cf6881415e/utils/DCN)
2. install anaconda and create a conda environment: `conda create -n my-env python=3.7`
3. install some packages: `conda install pytorch=1.3.1 torchvision cudatoolkit=10.0 pillow=6.1`
4. `sh make.sh`
