### ISSUE TITLE
_ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

### ISSUE THREAD

**Issue by KelvinHuang666** [chengdazhi/Deformable-Convolution-V2-PyTorch#50]
Traceback (most recent call last):
  File "demo.py", line 136, in <module>
    demo()
  File "demo.py", line 82, in demo
    from models.yolov3_baseline import YOLOv3
  File "/asff/models/yolov3_baseline.py", line 5, in <module>
    from .network_blocks import *
  File "/asff/models/network_blocks.py", line 5, in <module>
    from utils.DCN.modules.deform_conv2d import DeformConv2d
  File "/asff/utils/DCN/modules/__init__.py", line 1, in <module>
    from .deform_conv2d import DeformConv2d, _DeformConv2d, DeformConv2dPack, DeformConv2dPackMore
  File "/asff/utils/DCN/modules/deform_conv2d.py", line 12, in <module>
    from ..functions.deform_conv2d_func import DeformConv2dFunction
  File "/asff/utils/DCN/functions/__init__.py", line 1, in <module>
    from .deform_conv2d_func import DeformConv2dFunction
  File "/asff/utils/DCN/functions/deform_conv2d_func.py", line 13, in <module>
    import DCN
ImportError: /usr/local/lib/python3.6/dist-packages/DCN-1.0-py3.6-linux-x86_64.egg/DCN.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
root@0ad4f68fc474:/asff#

**Comment by kernel-Peanut** [comment]
have you solved this problem?

**Comment by kernel-Peanut** [comment]
Downgrade your pytorch version to 1.1.0 can clear up the error
