### ISSUE TITLE
Error when running python test

### ISSUE THREAD

**Issue by Susan19900316** [chengdazhi/Deformable-Convolution-V2-PyTorch#57]
I compiled the branch of pytorch1.0.0 sucesssully. But when I run python test.py, errors occured as follows:
error in deformable_im2col_cuda: invalid device function
error in deformable_col2im_coord_cuda: invalid device function
error in deformable_col2im_cuda: invalid device function
error in deformable_im2col_cuda: invalid device function
torch.Size([2, 128, 128, 128])
error in modulated_deformable_im2col_cuda: invalid device function
error in modulated_deformable_col2im_coord_cuda: invalid device function
error in modulated_deformable_col2im_cuda: invalid device function
error in modulated_deformable_im2col_cuda: invalid device function
torch.Size([2, 128, 128, 128])
HCudaCheck FAIL file=/media/zy/data/TDAN-VSR-CVPR-2020/src/cuda/deform_psroi_pooling_cuda.cu line=339 error=98 : unrecognized error code
Traceback (most recent call last):
  File "test.py", line 607, in <module>
    example_dpooling()
  File "test.py", line 561, in example_dpooling
    out = pooling(input, rois, offset)
  File "/software/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/TDAN-VSR-CVPR-2020/modules/deform_psroi_pooling.py", line 46, in forward
    self.trans_std)
  File "/data/TDAN-VSR-CVPR-2020/functions/deform_psroi_pooling_func.py", line 40, in forward
    ctx.sample_per_part, ctx.trans_std)
RuntimeError: cuda runtime error (98) : unrecognized error code at /media/zy/data/TDAN-VSR-CVPR-2020/src/cuda/deform_psroi_pooling_cuda.cu:339
[1]    17395 segmentation fault  python test.py

**Comment by MurrayC7** [comment]
@Susan19900316 Did you solve this problem? I'm also stuck here :(
