### ISSUE TITLE
depriciated torch.utils.ffi used 

### ISSUE THREAD

**Issue by research-boy** [chengdazhi/Deformable-Convolution-V2-PyTorch#64]
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Traceback (most recent call last):
  File "build_modulated.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by JamesZhan107** [comment]
Have you solved this problem？ @research-boy

**Comment by research-boy** [comment]
@JamesZhan107 Not yet, let me know if you can help me with this

**Comment by JamesZhan107** [comment]
> @JamesZhan107 Not yet, let me know if you can help me with this

https://github.com/ruinmessi/ASFF/tree/09f558863ae297663ec476f52a90c0cf6881415e/utils/DCN
This repo used dcnv2 and has modified the module. It can be complied.

**Comment by chengdazhi** [comment]
If you guys are using more up to date pytorch, you can checkout the deformable conv module in mmdetection repo.

**Comment by JamesZhan107** [comment]
`inputs = Variable(torch.randn(N, inC, inH, inW).cuda(), requires_grad=True)
offset = conv(**inputs**)
#offset = Variable(torch.randn(N, num_deformable_groups * 2 * kH * kW, inH, inW).cuda(), requires_grad=True)
output = conv_offset2d(**inputs**, offset)`
As is shown in test.py, Are these two inputs the same ？

**Comment by JamesZhan107** [comment]
‘’‘
’inputs = Variable(torch.randn(N, inC, inH, inW).cuda(), requires_grad=True)
offset = conv(**inputs**)
#offset = Variable(torch.randn(N, num_deformable_groups * 2 * kH * kW, inH, inW).cuda(), requires_grad=True)
output = conv_offset2d(**inputs**, offset)
‘’’
As is shown in test.py, are these two inputs the same?

**Comment by JamesZhan107** [comment]
‘’‘
inputs = Variable(torch.randn(N, inC, inH, inW).cuda(), requires_grad=True)
offset = conv(inputs)
#offset = Variable(torch.randn(N, num_deformable_groups * 2 * kH * kW, inH, inW).cuda(), requires_grad=True)
output = conv_offset2d(inputs, offset)
‘’’
As is shown in test.py, are these two inputs the same? @chengdazhi

**Comment by chengdazhi** [comment]
Yep

**Comment by JamesZhan107** [comment]
> Yep

OK, Thanks you !

**Comment by herbertcai** [comment]
Hi @chengdazhi,

I tried the DCN from here: https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/tree/mmdetection/mmdet/ops/dcn. It still gives the depreciation error. I then went to the official mmdetection repo https://github.com/open-mmlab/mmdetection, but couldn't find the DCN module. Could you point me to the right location?

Thanks!
